### ISSUE TITLE
Compton not running at startup

### ISSUE THREAD

**Issue by Shivsharma779** [HikariKnight/material-awesome#3] opened 2020-06-27 08:23 UTC
This line
 'compton --config ' .. filesystem.get_configuration_dir() .. '/configuration/compton.conf',
in my ~/.config/awesome/configuration/appls.lua.txt is not able to run compton at the startup

[apps.lua.txt](https://github.com/HikariKnight/material-awesome/files/4840182/apps.lua.txt)

**Comment by digitalsparky** [comment] 2020-08-07 17:51
Hi @Shivsharma779 

Does ~/.config/awesome/configuration/compton.conf exist for you? 

Try running the following in the terminal:

```
compton --config ~/.config/awesome/configuration/compton.conf
```

Is there any output from that command? errors etc?

I'm running this on a freshly git cloned copy of this repo, so my compton.conf is same as what is in this repo, and it's working fine for me.

Matt

**Comment by HikariKnight** [comment] 2021-02-24 17:59
compton is either not installed, not in your $PATH or you changed something in your config to make it not launch
or your compton.conf does not exist.

Closing this as the issue is for the awesome4.3-stable build

**Closed as completed by HikariKnight** 2021-02-24 17:59 UTC
